# Generated by Django 4.1.7 on 2023-06-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryModels',
            fields=[
                ('Sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Phone', models.IntegerField()),
                ('email_address', models.CharField(max_length=60)),
                ('City', models.CharField(max_length=80)),
                ('our_packages', models.CharField(choices=[('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze')], max_length=70)),
            ],
        ),
    ]
